FROM node:16.16.0

RUN mkdir -p /usr/src/app/backend

WORKDIR /usr/src/app/backend

COPY ./backend/package*.json ./

RUN npm install

COPY ./backend .

RUN make install_babel

EXPOSE 5000

CMD [ "npm", "run", "start:dev" ]